t1=[3,6,9,10,25,38,70]
a=input("enter number: ")
t1.append(a)
# print(t1)
# print("sum:",sum(t1))
# print("max:",max(t1))
# print("min:",min(t1))
# t1.sort()
# print("sort ascending: ",t1)
# t1.sort(reverse=True)
# print("sort descending:",t1)
# tuple=list(t1)
# print(tuple)
 
# t1.clear()
print(t1)